import React from "react";
import { AnimatedText } from "../_components/AnimatedText";
import Image from "next/image";
import Backend from "../_roadmaps/backend6.png"; // Ensure this path is correct

const Roadmaps = () => {
  return (
    <div className="flex flex-col items-center">
      {/* Animated Text Component */}
      <AnimatedText
        text="Backend"
        textClassName="text-[4rem] md:text-[6rem] font-bold"
      />

      {/* Text below the animated text */}
      <div className="mt-8 text-center text-lg md:text-xl px-4 z-10 text-white">
        <p>
          <strong>Backend development</strong> refers to the server-side aspect of web development, focusing on creating and managing the server logic, databases, and APIs. It involves handling user authentication, authorization, and processing user requests, typically using backend development languages such as Python, Java, Ruby, PHP, JavaScript (Node.js), and .NET.
        </p>
        <p className="mt-4">
          <strong>What does a Backend Developer do?</strong><br />
          A backend developer focuses on creating and maintaining the server-side components of web applications. They are primarily tasked with developing server-side APIs, handling database operations, and ensuring that the backend can manage high traffic volumes efficiently. Key responsibilities include integrating external services such as payment gateways and cloud services, and enhancing the performance and scalability of systems. This role is crucial for processing and securing data, serving as the backbone that supports frontend developers in delivering a seamless user experience.
        </p>
      </div>

      {/* Image in the center below the text */}
      <div className="mt-8 z-10 relative">
      <Image
        src={Backend}
        alt="Backend Image"
        useMap="#image-map"
        width={1200}
        height={800}
        layout="intrinsic"
      />
      {/* Image Map Generated by http://www.image-map.net/ */}
      <map name="image-map">
      <area target="_blank" alt="Artical" title="Artical" href="https://roadmap.sh/guides/what-is-internet" coords="456,266,725,315" shape="rect" />
<area target="_blank" alt="DNS" title="DNS" href="https://www.cloudflare.com/en-gb/learning/dns/what-is-dns/" coords="850,225,1126,263" shape="rect" />
<area target="_blank" alt="Domain Name" title="Domain Name" href="https://developer.mozilla.org/en-US/docs/Learn_web_development/Howto/Web_mechanics/What_is_a_domain_name" coords="850,271,1127,307" shape="rect" />
<area target="_blank" alt="Hosting" title="Hosting" href="https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started/Environment_setup/Browsing_the_web" coords="851,318,1126,353" shape="rect" />
<area target="_blank" alt="Internet Works" title="Internet Works" href="https://roadmap.sh/guides/what-is-internet" coords="60,226,356,265" shape="rect" />
<area target="_blank" alt="Http" title="Http" href="https://www.youtube.com/watch?v=2JYT5f2isg4" coords="61,274,355,310" shape="rect" />
<area target="_blank" alt="Browser Works" title="Browser Works" href="https://www.ramotion.com/blog/what-is-web-browser/" coords="61,319,357,354" shape="rect" />
<area target="_blank" alt="Js" title="Js" href="https://www.youtube.com/watch?v=hdI2bqOjy3c&amp;t=2s" coords="229,564,362,600" shape="rect" />
<area target="_blank" alt="Go" title="Go" href="https://www.youtube.com/watch?v=un6ZyFkqFKo" coords="359,433,226,397" shape="rect" />
<area target="_blank" alt="Python" title="Python" href="https://www.youtube.com/watch?v=ix9cRaBkVe0" coords="229,610,362,645" shape="rect" />
<area target="_blank" alt="Ruby" title="Ruby" href="https://www.youtube.com/playlist?list=PL_EzhIKp343lBMH4UuklrMRL_WkilGoXe" coords="230,656,363,693" shape="rect" />
<area target="_blank" alt="Java" title="Java" href="https://www.youtube.com/watch?v=xk4_1vDrzzo" coords="63,562,196,600" shape="rect" />
<area target="_blank" alt="C#" title="C#" href="https://www.youtube.com/watch?v=YrtFtdTTfv0" coords="64,612,197,648" shape="rect" />
<area target="_blank" alt="PHP" title="PHP" href="https://www.youtube.com/watch?v=zZ6vybT1HQs" coords="63,656,196,691" shape="rect" />
<area target="_blank" alt="Rust" title="Rust" href="https://www.youtube.com/watch?v=BpPEoZW5IiY" coords="62,400,193,434" shape="rect" />
<area target="_blank" alt="VCS" title="VCS" href="https://www.youtube.com/watch?v=SVkuliabq4g" coords="553,473,832,519" shape="rect" />
<area target="_blank" alt="Git" title="Git" href="https://www.youtube.com/watch?v=SWYqp7iY_Tc" coords="741,394,834,440" shape="rect" />
<area target="_blank" alt="Github" title="Github" href="https://www.youtube.com/watch?v=RGOj5yH7evk" coords="950,424,1076,469" shape="rect" />
<area target="_blank" alt="GitLab" title="GitLab" href="https://www.youtube.com/watch?v=bnF7f1zGpo4" coords="950,477,1077,521" shape="rect" />
<area target="_blank" alt="Bitbucket" title="Bitbucket" href="https://www.youtube.com/watch?v=M44nEyd_5To" coords="950,531,1077,577" shape="rect" />
<area target="_blank" alt="PostgreSQL" title="PostgreSQL" href="https://neon.tech/postgresql/tutorial" coords="51,741,235,776" shape="rect" />
<area target="_blank" alt="MySQL" title="MySQL" href="https://www.mysqltutorial.org/" coords="51,786,238,821" shape="rect" />
<area target="_blank" alt="MariaDB" title="MariaDB" href="https://www.youtube.com/watch?v=_AMj02sANpI" coords="49,830,237,866" shape="rect" />
<area target="_blank" alt="MS SQL" title="MS SQL" href="https://www.youtube.com/watch?v=-EPMOaV7h_Q" coords="50,875,237,911" shape="rect" />
<area target="_blank" alt="Oracle" title="Oracle" href="https://www.youtube.com/watch?v=ObbNGhcxXJA" coords="49,923,237,958" shape="rect" />
<area target="_blank" alt="Redis" title="Redis" href="https://www.youtube.com/watch?v=XCsS_NVAa1g" coords="62,1305,201,1344" shape="rect" />
<area target="_blank" alt="MongoDB" title="MongoDB" href="https://learn.mongodb.com/catalog" coords="66,1006,197,1045" shape="rect" />
<area target="_blank" alt="InfluxDB" title="InfluxDB" href="https://www.youtube.com/watch?v=wBWTj-1XiRU" coords="364,1045,233,1005" shape="rect" />
<area target="_blank" alt="couch" title="couch" href="https://docs.couchdb.org/en/stable/" coords="65,1054,198,1091" shape="rect" />
<area target="_blank" alt="timescale" title="timescale" href="https://www.timescale.com/" coords="234,1052,365,1091" shape="rect" />
<area target="_blank" alt="DynamoDB" title="DynamoDB" href="https://www.youtube.com/watch?v=2k2GINpO308" coords="61,1351,202,1390" shape="rect" />
<area target="_blank" alt="firebase" title="firebase" href="https://firebase.google.com/docs" coords="66,1155,200,1191" shape="rect" />
<area target="_blank" alt="rethinkDB" title="rethinkDB" href="https://www.youtube.com/watch?v=pW3PFtchHDc" coords="66,1202,198,1242" shape="rect" />
<area target="_blank" alt="Cassandra" title="Cassandra" href="https://www.youtube.com/watch?v=J-cSy5MeMOA" coords="233,1154,364,1193" shape="rect" />
<area target="_blank" alt="Base" title="Base" href="https://docs.oracle.com/en-us/iaas/base-database/index.html" coords="230,1202,363,1239" shape="rect" />
<area target="_blank" alt="neo4j" title="neo4j" href="https://www.youtube.com/watch?v=_IgbB24scLI" coords="229,1304,369,1342" shape="rect" />
<area target="_blank" alt="ORMs" title="ORMs" href="https://stackoverflow.com/questions/1279613/what-is-an-orm-how-does-it-work-and-how-should-i-use-one/1279678#1279678" coords="435,1069,602,1105" shape="rect" />
<area target="_blank" alt="ACID" title="ACID" href="https://fauna.com/blog/what-is-acid-compliance-atomicity-consistency-isolation" coords="435,1115,602,1150" shape="rect" />
<area target="_blank" alt="Transaction" title="Transaction" href="https://fauna.com/blog/database-transaction" coords="433,1160,604,1196" shape="rect" />
<area target="_blank" alt="N+1" title="N+1" href="https://medium.com/doctolib/understanding-and-fixing-n-1-query-30623109fe89" coords="435,1203,601,1238" shape="rect" />
<area target="_blank" alt="normalization" title="normalization" href="https://www.guru99.com/database-normalization.html" coords="434,1247,605,1285" shape="rect" />
<area target="_blank" alt="indexing" title="indexing" href="https://www.youtube.com/watch?v=9-Wv4al1XB4" coords="434,1292,604,1330" shape="rect" />
<area target="_blank" alt="replication" title="replication" href="https://www.youtube.com/watch?v=LKvtcwj5zjA" coords="431,1337,603,1374" shape="rect" />
<area target="_blank" alt="sharding" title="sharding" href="https://www.youtube.com/watch?v=chE52a5dMlQ" coords="432,1382,604,1421" shape="rect" />

      </map>
    </div>
  
    </div>
  );
};

export default Roadmaps;
