import React from "react";
import { AnimatedText } from "../_components/AnimatedText";
import Image from "next/image";
import Mongodb from "../_roadmaps/mongodb.png"; // Ensure this path is correct

const Roadmaps = () => {
  return (
    <div className="flex flex-col items-center">
      {/* Animated Text Component */}
      <AnimatedText
        text="Mongo DB"
        textClassName="text-[4rem] md:text-[6rem] font-bold"
      />

      {/* Text below the animated text */}
      <div className="mt-8 text-center text-lg md:text-xl px-4 z-10 text-white">
        <p>
          <strong>What is MongoDB?</strong> MongoDB is an open-source, document-based, and cross-platform NoSQL database that offers high performance, high availability, and easy scalability. It differs from traditional relational databases by utilizing a flexible, schema-less data model built on top of BSON (Binary JSON), allowing for non-structured data to be easily stored and queried.
        </p>
        <p className="mt-4">
          <strong>Key Features of MongoDB?          </strong><br />
          Document-oriented: MongoDB stores data in JSON-like documents (BSON format), meaning that the data model is very flexible and can adapt to real-world object representations easily.

Scalability: MongoDB offers automatic scaling, as it can be scaled horizontally by sharding (partitioning data across multiple servers) and vertically by adding storage capacity.

Indexing: To enhance query performance, MongoDB supports indexing on any attribute within a document.

Replication: MongoDB provides high availability through replica sets, which are primary and secondary nodes that maintain copies of the data.

Aggregation: MongoDB features a powerful aggregation framework to perform complex data operations, such as transformations, filtering, and sorting.

Support for ad hoc queries: MongoDB supports searching by field, range, and regular expression queries.
        </p>
      </div>

      {/* Image in the center below the text */}
      <div className="mt-8 z-10 relative">
      <Image
        src={Mongodb}
        alt="Backend Image"
        useMap="#image-map"
        width={1200}
        height={800}
        layout="intrinsic"
      />
      {/* Image Map Generated by http://www.image-map.net/ */}

    </div>
  
    </div>
  );
};

export default Roadmaps;
