import React from "react";
import { AnimatedText } from "../_components/AnimatedText";
import Image from "next/image";
import DevOps from "../_roadmaps/devops.png"; // Ensure this path is correct

const Roadmaps = () => {
  return (
    <div className="flex flex-col items-center">
      {/* Animated Text Component */}
      <AnimatedText
        text="DevOps"
        textClassName="text-[4rem] md:text-[6rem] font-bold"
      />

      {/* Text below the animated text */}
      <div className="mt-8 text-center text-lg md:text-xl px-4 z-10 text-white">
        <p>
          <strong>What is DevOps?</strong> DevOps is a cultural and collaborative mindset that emphasizes communication, collaboration, integration, and automation between development and operations teams in order to achieve faster and more reliable software delivery.

DevOps is not a specific job title or role, but rather a set of principles and practices that can be applied across a variety of roles in software development and IT operations. Anyone involved in the software development and delivery process can adopt a DevOps mindset and apply DevOps practices in their work, including developers, testers, operations engineers, product managers, and others.
        </p>
        <p className="mt-4">
          <strong>What is a DevOps Engineer?</strong><br />
          While DevOps is not a specific job title or role, organizations often hire for a "DevOps Engineer" role. A DevOps Engineer is a software engineer who specializes in the practices and tools that enable the continuous delivery of software. DevOps Engineers are responsible for the design and implementation of applications, software, and services for their organization, and they work closely with developers, testers, and operations staff to oversee the code releases.
        </p>
      </div>

      {/* Image in the center below the text */}
      <div className="mt-8 z-10 relative">
      <Image
        src={DevOps}
        alt="Backend Image"
        useMap="#image-map"
        width={1200}
        height={800}
        layout="intrinsic"
      />
      {/* Image Map Generated by http://www.image-map.net/ */}
      
    </div>
  
    </div>
  );
};

export default Roadmaps;
